import pkg from '../../../package.json';

export const SKILL_MARKDOWN = [
  '---',
  'name: sprint',
  'description: Automatically adds, registers, and manages codebases/projects in Sprint (the high-performance Rust-powered developer process supervisor). Use when the user types /sprint or asks to register, track, configure, or inspect projects in Sprint.',
  '---',
  '',
  '# Sprint v' + pkg.version + ' Project Supervisor Skill',
  '',
  'This skill registers, configures, and manages active codebase projects in **Sprint** (`%APPDATA%\\sprint\\projects.json`).',
  '',
  '## System Architecture',
  '',
  '- **GitHub Repository**: [NALYD2400/portly](https://github.com/NALYD2400/portly)',
  '- **Config Storage**: `%APPDATA%\\sprint\\projects.json`',
  '- **Native Rust Engine**: Process manager with asynchronous stdout/stderr log streaming and real-time CPU/RAM telemetry polling (every 2s).',
  '- **Auto-Stop Child Processes on Exit**: On app exit or tray quit, Sprint terminates all spawned dev servers (taskkill /F /T) to prevent orphaned processes.',
  '- **Auto-Restart & RAM Guard**: Servers that crash (or exceed their configured RAM limit) are automatically restarted with a cooldown.',
  '- **In-App Auto-Updater**: Connects to GitHub Releases with signature-domain validation and an animated progress modal.',
  '',
  '---',
  '',
  '## Workflow: Registering a Project (/sprint)',
  '',
  '1. **Detect Stack & Dev Commands**:',
  '   - **Root Path**: Workspace root directory.',
  '   - **Project Name**: Folder basename or `name` field in `package.json` / `Cargo.toml`.',
  '   - **Framework Detection Rules**:',
  '     - **Next.js / Vite / React / Vue / Svelte / Astro**: `npm run dev` (Port 3000 or 5173)',
  '     - **Tauri / Rust**: `npm run tauri dev` or `cargo run`',
  '     - **Express / NestJS / Node**: `node server.js` or `npm run start:dev`',
  '     - **Python (FastAPI/Flask/Django)**:',
  '       `python main.py` or `uvicorn main:app --reload` (Port 8000)',
  '     - **Go**: `go run .` (Port 8080)',
  '',
  '2. **Update projects.json**:',
  '   - Read `%APPDATA%\\sprint\\projects.json`.',
  '   - If `root == current_workspace_root` exists, update dev commands if needed.',
  '   - If missing, append a new project configuration with servers.',
  '   - Save formatted JSON back.',
  '',
  '3. **User Confirmation**:',
  '   - Return a concise markdown summary confirming project registration, detected stack, assigned port, and dev command.',
].join('\n');
